server:
    port: 8763

logging:
    level:
      com:
        netflix:
          eureka: OFF
          discovery: OFF
#management:
#  security:
#    enabled: false


eureka:
#  instance:
#      statusPageUrlPath: http://localhost:8761/info
#      healthCheckUrlPath: http://localhost:8761/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
    name: huawei
    email: 120huawei@163.com