server:
    port: 8762

logging:
    level:
      com:
        netflix:
          eureka: OFF
          discovery: OFF
management:
  security:
    enabled: false


eureka:
  instance:
#    instance-id: localhost:8761
    lease-renewal-interval-in-seconds: 2 #契约更新间隔
    lease-expiration-duration-in-seconds: 4 #契约过期时间
#    statusPageUrlPath: http://localhost:8761/info
#    healthCheckUrlPath: http://localhost:8761/health
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 1

feign:
  hystrix:
    enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false